routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::resource('/profile','ProfileController');
Route::resource('/group','GroupController',['only' => ['index', 'create','store']]);

Route::get('group/addUser','GroupController@AddUser')->name('addUser');
Route::post('group/addUser','GroupController@StoreAddUser')->name('StoreAddUser');

Route::get('/sendsms','SmsController@index');

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public function profiles(){
        return $this->belongsToMany(Profile::class);
    }
}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public function type(){

       return $this->belongsTo(Type::class);
    }

    public function group()
    {
        return $this->belongsTo('App\Group');
    }

    public function groups(){
        return $this->belongsToMany(Group::class);
    }
}

app/Type.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Type extends Model
{
    protected $table = 'user_types';

    public function profiles(){

       return $this->hasMany(Profile::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Profile;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    public function index(){

        $groups=Group::all();

        return view('group_index',compact('groups'));
    }

    public function create(){
        $profiles=Profile::all();
        return view('group_create',compact('profiles'));
    }

    public function store(Request $request){

        $group=new Group();

        $group->name=$request->name;

        $group->save();

        return back()->with(['success' => "{$request->name} registered"]);

    }

    public function AddUser(){
        $groups=Group::all();
        $profiles=Profile::all();
        return view('add_users_to_group',compact('profiles','groups'));
    }

    public function StoreAddUser(Request $request){

        $group=Group::findorfail($request->group);
        $group->save();
        $group->profiles()->attach($request->profiles);
        return back()->with(['success' => "{$request->name} registered"]);
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Profile;
use App\Type;
use Illuminate\Http\Request;
use Illuminate\Validation\Rules\RequiredIf;

class ProfileController extends Controller
{

    public function index()
    {
        $profiles = Profile::all();
        return view('profile_index', compact('profiles'));
    }

    public function create()
    {
        $types = Type::all();

        return view('profile_create', compact('types'));
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'type' => 'required',
            'name' => 'required',
            'email' => 'required|email',
            'phone_number' => 'required|numeric',
            'tax_number' => new RequiredIf($request->type == 2, 'numeric')
        ]);

        $profile = new Profile();

        $profile->type_id = $request->type;
        $profile->name = $request->name;
        $profile->email = $request->email;
        $profile->phone_number = $request->phone_number;
        $profile->tax_number = $request->tax_number;

        $profile->save();
        return back()->with(['success' => "{$request->name} registered"]);
    }


    public function edit($id)
    {
        $profile = Profile::findOrFail($id);

        $types = Type::all();

        return view('profile_edit', compact('profile', 'types'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'type' => 'required',
            'name' => 'required',
            'email' => 'required|email',
            'phone_number' => 'required|numeric',
            'tax_number' => new RequiredIf($request->type == 2, 'numeric')
        ]);

        $profile = Profile::findOrFail($id);

        $profile->type_id = $request->type;
        $profile->name = $request->name;
        $profile->email = $request->email;
        $profile->phone_number = $request->phone_number;

        if ($request->type == 2) {
            $profile->tax_number = $request->tax_number;
        } else
            $profile->tax_number = null;
        $profile->save();
        return back()->with(['success' => "{$request->name} updated"]);
    }


    public function destroy($id)
    {
        $profile = Profile::findOrFail($id)->delete();

        return back()->with(['success' => "user deleted"]);
    }
}

app/Http/Controllers/SmsController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Profile;
use http\Client;
use Illuminate\Http\Request;

class SmsController extends Controller
{
    public function index(){
        $groups=Group::all();
        $profiles=Profile::all();

        $alls=$groups->merge($profiles);

        return view('send_sms',compact('alls'));
    }

    public function sendCustomMessage(Request $request)
    {
        $validate = $request->validate([
            'profiles' => 'required|array',
            'body' => 'required',
        ]);
        $profiles = $validate["profiles"];
        foreach ($profiles as $profile) {
            $this->sendMessage($validate["body"], $profile);
        }
        return back()->with(['success' => "Sms sent"]);
    }
    private function sendMessage($message, $recipients)
    {
        //sms provider
        $account_sid = getenv("acc of the sms provider api");
        $auth_token = getenv("auth token");
        $number = getenv("phone number to send from");

        $client = new Client($account_sid, $auth_token);
        $client->messages->create($recipients, array('from' => $number, 'body' => $message));
    }

}

resources/views/add_users_to_group.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="jumbotron">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="card">
                <div class="card-header">
                    Add Profiles to Group
                </div>
                <div class="card-body">
                    <form method="POST" action="{{route('StoreAddUser')}}">
                        @csrf

                        <div class="form-group">
                            <label>Group</label>
                            <select id="group" class="form-control" name="group">
                                <option disabled selected>Chose one</option>
                                @foreach($groups as $group)
                                    <option value="{{$group->id}}">{{$group->name}}</option>
                                @endforeach
                            </select>

                        </div>

                        <div class="form-group">
                            <label>Select users to notify</label>
                            <select name="profiles[]" multiple class="form-control">
                                @foreach ($profiles as $profile)
                                    <option>{{$profile->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/group_create.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="jumbotron">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            Add Group
                        </div>
                        <div class="card-body">

                            <form method="POST" action="{{route('group.store')}}">
                                @csrf
                                <div class="form-group">
                                    <label>Enter Name of the Group</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter Name of the Group">
                                </div>

                                <button type="submit" class="btn btn-primary">Register</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/group_index.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="jumbotron">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <div class="card-header">
                    <a href="{{route('group.create')}}" class="btn btn-info">To add group Click here</a>

                </div>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created At:</th>
                    <th>Updated At:</th>

                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created At:</th>
                    <th>Updated At:</th>
                </tr>
                </tfoot>
                <tbody>
                @foreach($groups as $key=>$group)
                    <tr>
                        <td>{{$key + 1 }}</td>
                        <td>{{$group->name }}</td>
                        <td>{{$group->created_at }}</td>
                        <td>{{$group->updated_at }}</td>
                    </tr>
                @endforeach


                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">

    <style>
        #hidden_div {
            display: none;
        }
    </style>
</head>
<body>
@yield('content')
<script>
    function changeid()
    {
        var e = document.getElementById("c");
        e.id = "hidden_div";
    }
    function showDiv(divId, element)
    {
        document.getElementById(divId).style.display = element.value == 2 ? 'block' : 'none';
    }
</script>

</body>
</html>

resources/views/profile_create.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="jumbotron">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            Add Profile
                        </div>
                        <div class="card-body">

                            <form method="POST" action="{{route('profile.store')}}">
                                @csrf
                                <div class="form-group">
                                    <label>Profile Type</label>
                                    <select id="test" class="form-control" name="type" onchange="showDiv('hidden_div', this)">
                                        <option disabled selected>Chose one</option>
                                        @foreach($types as $type)
                                            <option value="{{$type->id}}">{{$type->name}}</option>
                                        @endforeach
                                    </select>

                                </div>
                                <div class="form-group">
                                    <label>Enter Name and Surname</label>
                                    <input type="text" class="form-control" name="name" placeholder="Enter Name">
                                </div>
                                <div class="form-group">
                                    <label>Enter Email</label>
                                    <input type="tel" class="form-control" name="email" placeholder="Enter Email">
                                </div>
                                <div class="form-group">
                                    <label>Enter Phone Number</label>
                                    <input type="tel" class="form-control" name="phone_number"
                                           placeholder="Enter Phone Number">
                                </div>

                                <div class="form-group" id="hidden_div">
                                    <label>Enter Tax number</label>
                                    <input type="number" class="form-control" name="tax_number"
                                           placeholder="Enter Tax-Number">
                                </div>

                                <button type="submit" class="btn btn-primary">Register</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/profile_edit.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
          crossorigin="anonymous">

    <style>
        #hidden_div {
            display: none;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="jumbotron">
        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        Add Profile
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{route('profile.update',$profile->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label>Profile Type</label>
                                <select id="test" class="form-control" name="type" onchange="showDiv('hidden_div', this)">
                                    @foreach($types as $type)
                                        <option {{$type->id ==$profile->type_id ? 'selected':''}} value="{{$type->id}}">
                                            {{$type->name}}
                                        </option>
                                    @endforeach
                                </select>

                            </div>

                            <div class="form-group">
                                <label>Enter Name and Surname</label>
                                <input type="text" class="form-control" value="{{$profile->name}}" name="name" placeholder="Enter Name">
                            </div>

                            <div class="form-group">
                                <label>Enter Email</label>
                                <input type="tel" class="form-control" value="{{$profile->email}}"name="email" placeholder="Enter Email">
                            </div>

                            <div class="form-group">
                                <label>Enter Phone Number</label>
                                <input type="tel" class="form-control" name="phone_number" value="{{$profile->phone_number}}"
                                       placeholder="Enter Phone Number">
                            </div>

                            @if($profile->type_id==2)

                                <div class="form-group" id="hidden_div">
                                    <label>Enter Tax number</label>
                                    <input type="number" class="form-control" name="tax_number" value="{{$profile->tax_number}}"
                                           placeholder="Enter Tax-Number">
                                </div>

                            @elseif($profile->type_id==1)

                                <div class="form-group" id="hidden_div">
                                    <label>Enter Tax number</label>
                                    <input type="number" class="form-control" name="tax_number" value="{{$profile->tax_number}}"
                                           placeholder="Enter Tax-Number">
                                </div>

                            @endif


                            <button type="submit" class="btn btn-primary">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function changeid()
    {
        var e = document.getElementById("c");
        e.id = "hidden_div";
    }
    function showDiv(divId, element)
    {
        document.getElementById(divId).style.display = element.value == 2 ? 'block' : 'none';
    }
</script>

</body>
</html>

resources/views/profile_index.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="jumbotron">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
                <div class="card-header">
                    <a href="{{route('profile.create')}}" class="btn btn-info">To add profile Click here</a>

                </div>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Name and Surname</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Tax number</th>
                    <th>Created At:</th>
                    <th>Updated At:</th>
                    <th>Actions:</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Name and Surname</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Tax number</th>
                    <th>Created At:</th>
                    <th>Updated At:</th>
                    <th>Actions:</th>
                </tr>
                </tfoot>
                <tbody>
                @foreach($profiles as $key=>$profile)
                    <tr>
                        <td>{{$key + 1 }}</td>
                        <td>{{$profile->type->name }}</td>
                        <td>{{$profile->name }}</td>
                        <td>{{$profile->email}}</td>
                        <td>{{$profile->phone_number}}</td>
                        <td>
                            @if($profile->tax_number==null)
                                No Tax Number this is an Individual
                                @else
                                {{$profile->tax_number}}
                            @endif
                        </td>
                        <td>{{$profile->created_at }}</td>
                        <td>{{$profile->updated_at }}</td>
                        <td class="text-center">
                            <a href="{{route('profile.edit',$profile->id)}}">
                                <button class="btn btn-success">  EDIT</button>

                            </a>

                                <form
                                    id="delete-form-{{$profile->id}}"
                                    action="{{route('profile.destroy',$profile->id)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                <button type="button" class="btn btn-danger"
                                        onclick="if(confirm('Are you sure'))
                                            {
                                            event.preventDefault();
                                            document.getElementById('delete-form-{{$profile->id}}').submit();
                                            }
                                            ">
                                    Delete
                                </button>




                        </td>

                    </tr>
                @endforeach


                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/send_sms.blade.php
@extends('layout')

@section('content')
<div class="container">
    <div class="jumbotron">
        @if (session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

                    <div class="card-header">
                        Send SMS message
                    </div>
                    <div class="card-body">
                        <form method="POST" action="/custom">
                            @csrf
                            <div class="form-group">
                                <label>Select users to profiles</label>
                                <select name="profiles[]" multiple class="form-control">
                                    @foreach ($alls as $all)
                                        <option>{{$all->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Notification Message</label>
                                <textarea name="body" class="form-control"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Send Notification</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection